# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: rajaman9355@gmail.com
author_name: Aman Raj Gupta
contract_name: ticketer_contracts
preset_name: production
project_name: ticketer-contracts

