# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: rajaman9355@gmail.com
author_name: Aman Raj Gupta
cloud_provider: none
contract_name: ticketer_contracts
preset_name: production
project_name: ticketer

